dist:     focal
sudo:     required
language: c
os: linux

install:
    - sudo apt-get update
    - sudo apt-get install --yes libgtest-dev
    - sudo apt-get install --yes gcovr

jobs:
    - stage: Build
      script:
        - cmake -B build -DCMAKE_BUILD_TYPE=Release
        - make -C build
    - stage: Test
      script:
        - cmake -B build -DCMAKE_BUILD_TYPE=Release -DWITH_TESTS=ON
        - make -C build
        - cd build && ctest --output-on-failure
