os:       linux
dist:     trusty
language: c

install:
 - sudo apt-get update
 - sudo apt-get --yes libgtest-dev
 - sudo apt-get --yes gcovr

jobs:
 - stage: Build
   script:
    - cmake -B build
    - make -C build
